[workspace]
resolver = "2"
members = [
    "mfp-lib",
]

[workspace.dependencies]
futures = "0.3.31"
tempfile = "3.16.0"
thiserror = "2.0.11"
tokio = { version = "1.43", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
