name: rust checks 

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: rustfmt, clippy

    - uses: Swatinem/rust-cache@v2

    - name: Build
      run: cargo build --verbose --all --locked

    - name: Run unit tests
      run: cargo test --locked -- --nocapture
      
    - name: Check clippy for all features
      run: cargo clippy --all-targets --all-features  -- -D warnings
    
    - name: Format
      run: cargo fmt --check